export const COHORT = {
  state: 'active' as 'active' | 'early' | 'soldout',
  date: 'Sep 30, 2026',
  dateShort: 'Sep 30',
  day: 'Wednesday',
  time: '7:00 PM IST / 9:30 AM US Eastern',
  seatsTotal: 20,
  seatsLeft: 10,
  prevCohortDate: 'Aug 27',
  studentsTotal: '250+',
  priceIndia: '₹7,999',
  priceIntl: '$149',
  originalPriceIndia: '₹15,999',
  originalPriceIntl: '$300',
  capstonePriceIndia: '₹1,000',
  capstonePriceIntl: '$49',
  priceTaglineIndia: "",
  priceTaglineIntl: "",
  pricePerSessionIndia: '₹2,666',
  pricePerSessionIntl: '$67',
  formUrl: 'https://learn.approachable.dev/registration',

  priceIncreaseAt: '2026-09-23T23:59:59+05:30',
  priceIncreaseDateShort: 'Sep 23',
  priceIndiaLate: '₹9,999',
  priceIntlLate: '$169',
  priceTaglineIndiaLate: "",
  priceTaglineIntlLate: "",
  pricePerSessionIndiaLate: '₹3,333',
  pricePerSessionIntlLate: '$83',
};
